<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="MassTransit.RabbitMQ" Version="9.1.2" />
    <PackageReference Include="Microsoft.Extensions.Http.Resilience" Version="10.7.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PartnerIntegration.BFF.Core\PartnerIntegration.BFF.Core.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
