services:
  partnerintegration.bff.api:
    image: ${DOCKER_REGISTRY-}partnerintegrationbffapi
    build:
      context: .
      dockerfile: PartnerIntegration.BFF.Api/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy

  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
